name = "webflow-predictive-search"
compatibility_date = "2024-02-01"
main = ".vercel/output/static/_worker.js"

[[migrations]]
tag = "v1"
new_classes = ["D1Database"]

[build]
command = "npm run build"
publish = ".vercel/output/static"

[build.upload]
format = "service-worker"
